### ISSUE TITLE
多个串口通信

### ISSUE THREAD

**Issue by Coulomb-engine** [GeekBugs/Android-SerialPort#10]
当我试图创建第二个SerialPortHelper时（使用第二个串口Port），发现打开的串口Port可能会覆盖第一个SerialPortHelper，如何解决呢

**Comment by Coulomb-engine** [comment]
我声明了两个mSerialPortHelper来引用两个SerialPortHelper实例（new了两个SerialPortHelper），当open第二个实例的串口时，调用第一个实例的close方法，会把第二个实例的串口关闭。

**Comment by Coulomb-engine** [comment]
我声明了两个mSerialPortHelper来引用两个SerialPortHelper实例（new了两个SerialPortHelper），当open第二个实例的串口后，调用第一个实例的close方法，会把第二个实例的串口关闭。

**Comment by F1ReKing** [comment]
这就很奇怪了，但我已经2年没接触串口实验开发项目了，没设备去调试了，暂时无法帮助到你

**Comment by fjasmin** [comment]
我也发现多个串口通讯 有问题

**Comment by MagicZhang1-ctrl** [comment]
> 我声明了两个mSerialPortHelper来引用两个SerialPortHelper实例（new了两个SerialPortHelper），当open第二个实例的串口后，调用第一个实例的close方法，会把第二个实例的串口关闭。

请问您是怎么解决的？我也是创建了多个SerialPortHelper的实例，发现不可以实现多串口通信。

**Comment by JamesGZM** [comment]
> > 我声明了两个mSerialPortHelper来引用两个SerialPortHelper实例（new了两个SerialPortHelper），当open第二个实例的串口后，调用第一个实例的close方法，会把第二个实例的串口关闭。
> 
> 请问您是怎么解决的？我也是创建了多个SerialPortHelper的实例，发现不可以实现多串口通信。

open 之前重新设置一下串口 因为他项目里面是 static 变量的串口名称

**Comment by JamesGZM** [comment]
> > 我声明了两个mSerialPortHelper来引用两个SerialPortHelper实例（new了两个SerialPortHelper），当open第二个实例的串口后，调用第一个实例的close方法，会把第二个实例的串口关闭。
> 
> 请问您是怎么解决的？我也是创建了多个SerialPortHelper的实例，发现不可以实现多串口通信。

我本来想提个 pr ，但是暂时没有空 需要把 static 的一些变量改掉
